name: virtual-human
channels:
  - conda-forge
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.51.0=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h725018a_0
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py310h1637853_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hc20f281_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=h2c6b04d_3
  - tornado=6.5.2=py310h29418f3_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.0.1
      - babel==2.17.0
      - bangla==0.0.5
      - blinker==1.9.0
      - blis==1.3.3
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.2.1
      - coqpit==0.0.17
      - ctranslate2==4.6.1
      - cycler==0.12.1
      - cymem==2.0.13
      - cython==3.2.1
      - dateparser==1.1.8
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - factor-analyzer==0.5.1
      - faster-whisper==1.2.1
      - filelock==3.20.0
      - flask==3.1.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - g2pkk==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h11==0.16.0
      - hangul-romanize==0.1.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.3.7
      - humanfriendly==10.0
      - idna==3.11
      - inflect==7.5.0
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonlines==1.2.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.10.0
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - murmurhash==1.0.15
      - narwhals==2.15.0
      - networkx==2.8.8
      - nltk==3.9.2
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.26.4
      - onnxruntime==1.23.2
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.2
      - patsy==1.0.2
      - pillow==10.4.0
      - pooch==1.8.2
      - preshed==3.0.12
      - propcache==0.4.1
      - protobuf==5.29.5
      - pyarrow==23.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pygame==2.6.1
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pypinyin==0.55.0
      - pyreadline3==3.5.4
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rich==13.9.4
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.11.4
      - shellingham==1.5.4
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - statsmodels==0.14.5
      - streamlit==1.36.0
      - sudachidict-core==20251022
      - sudachipy==0.6.10
      - sympy==1.14.0
      - tenacity==8.5.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - torch==2.9.1+cu126
      - torchaudio==2.9.1
      - torchcodec==0.8.1
      - torchvision==0.24.1+cu126
      - tqdm==4.67.1
      - trainer==0.0.36
      - transformers==5.0.0
      - tts==0.22.0
      - typeguard==4.4.4
      - typer-slim==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap-learn==0.5.7
      - unidecode==1.4.0
      - urllib3==2.5.0
      - wasabi==1.1.3
      - watchdog==4.0.2
      - weasel==0.4.3
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - yarl==1.22.0
prefix: C:\Users\17102\.conda\envs\virtual-human
